LAB_DESCRIPTION="Ejercicio de ruteo y NAT"
LAB_VERSION="1.0"
LAB_AUTHOR="Pablo Lavallen"
LAB_EMAIL="plavallen@unlu.edu.ar"


# Servidres web y de correo
web[image]="docentetyr/tyr-base-2023"
web[0]="A/02:A1:00:01:00:01"

# Servidores de bases de datos y aplicaciones
db[0]="B/02:B1:00:01:00:01"
db[image]="docentetyr/tyr-base-2023"

# Servidor proxy 
proxy[0]="D/02:C1:00:01:00:01"
proxy[image]="docentetyr/tyr-base-2023"

# Red de Usuarios
user[0]="C/02:D1:00:01:00:01"
user[image]="docentetyr/tyr-base-2023"

# Router del ISP
risp[0]="G/02:E1:00:01:00:01"
risp[image]="docentetyr/tyr-base-2023"

# Ruteadores de la Organizacion
r1[image]="docentetyr/tyr-base-2023"
r1[0]="D/02:F1:01:01:00:01"
r1[1]="F/02:F1:01:02:00:01"
r1[2]="A/02:F1:01:03:00:01"
r1[3]="G/02:F1:01:04:00:01"

r2[image]="docentetyr/tyr-base-2023"
r2[0]="C/02:F2:01:01:00:01"
r2[1]="B/02:F2:01:02:00:01"
r2[2]="F/02:F2:01:03:00:01"


r1[sysctl]="net.ipv4.ip_forward=1"
r2[sysctl]="net.ipv4.ip_forward=1"
risp[sysctl]="net.ipv4.ip_forward=1"


capturador[image]="docentetyr/tyr-base-2023"
capturador[0]="A"
capturador[1]="B"
capturador[2]="C"
capturador[3]="D"
capturador[4]="F"
capturador[5]="G"
capturador[ipv6]=false
capturador[mem]=64


